### PR TITLE
Multi layer colormap

### PR DESCRIPTION
**Pull request by jamesnvc**
Builds on #105 to allow Colormap to deal with multiple layers.

It works well for me on Linux, but I suspect that it may have the same issue with sending multiple layers that the keymaps did... @TheBaronHimself would you be able to test this?

### CODE REVIEW

**Comment by TheBaronHimself** [comment]
No problem, will test this as soon as possible.

**Comment by TheBaronHimself** [comment]
Unfortunately I'm having hardware issues with my Model 01 so I'm back to using my old keyboard. Can someone else test this?

**Comment by jamesnvc** [comment]
Simon-Claudius <notifications@github.com> writes:

> Unfortunately I'm having hardware issues with my Model 01 so I'm back to using my old keyboard. Can someone else test this?
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Lepidopterarium/Chrysalis/pull/109#issuecomment-343740127

I'll get my macOS laptop out at some point today or tomorrow & give it a try on that.

**Comment by jamesnvc** [comment]
Looks like the same sort of freezing-on-transfer issue as expected. I'll do the same thing as before & make the colormap plugin able to take updates one layer at a time.

**Comment by jamesnvc** [comment]
Okay, working; requires https://github.com/keyboardio/Kaleidoscope-LED-Palette-Theme/pull/4, https://github.com/keyboardio/Kaleidoscope-Colormap/pull/5, and adding `Focus.addHook(FOCUS_HOOK_COLORMAP_LAYER);` to the sketch.

**Comment by jamesnvc** [comment]
Above PRs have been merged, so folks should be able to update those libraries to newest & add the focus hook. @TheBaronHimself think this is reasonable to merge now? Once it's done, I'll update the Chrysalis fork of model01 firmware to work with this.

**Comment by TheBaronHimself** [comment]
Time to merge.

**Pull request merged**
