### PR TITLE
Upload by layer

### PR DESCRIPTION
**Pull request by jamesnvc**
Couple of things going on here; this also adds the ability to reset the eeprom-override for a layer by setting it to be all transparent (so it reads from progmem instead).

### CODE REVIEW

**Comment by jamesnvc** [comment]
Actually, commenting out the "reset to default" button as it seems to be causing weird things to happen.

**Comment by jamesnvc** [comment]
Still a definite work-in-progress here, trying to figure out some mysterious issues.

I tried changing reading the keymaps back from the EEPROM to read one layer at a time, but I'm seeing weird issues, like a bunch of extra zeros messing up the keymap when reading it back. These weird issues and occasionally keyboard-lockups only seem to happen when Layer.getKey == EEPROMKeymapper.getKeyOverride. I'm suspect a timing issue in trying to read/write from EEPROM too quickly maybe?

**Comment by jamesnvc** [comment]
Ahh...from Arduino docs: 

> This solution may save execution time because every write operation takes 3.3 ms

https://www.arduino.cc/en/Tutorial/EEPROMUpdate 

Maybe it is a race condition? Batching writes and using update may make this better, especially when writing keymaps with only a few things changed.

**Comment by jamesnvc** [comment]
Er, it already uses `update`, but maybe there's some other way we can make this more efficient? Still open to the possibility there's a logic bug somewhere.

**Comment by jamesnvc** [comment]
To use this branch: 
 - make sure you have the latest version of [EEPROM-Keyremapper](https://github.com/keyboardio/Kaleidoscope-EEPROM-Keymap) on the device (for the new layer-wise focus hooks) and add `FOCUS_HOOK_KEYMAP_LAYER` to the sketch.

**Comment by jamesnvc** [comment]
Now that this is working, shall we merge it in?

**Comment by TheBaronHimself** [comment]
No objections. Good work. @algernon?

**Pull request merged**
