### PR TITLE
ui.about: Update the credits

### PR DESCRIPTION
**Pull request by algernon**
James & Simon-Claudius have as much reason to be in there as I do, make it so.

### CODE REVIEW

**Comment by TheBaronHimself** [comment]
Thanks for this. Could you change my credit to Simon-Claudius Wystrach and the link to simonclaudius.com?

**Comment by algernon** [comment]
Sure. Will do that later tonight!

**Comment by algernon** [comment]
Done!

**Comment by TheBaronHimself** [comment]
Thanks :).

**Pull request merged**
